name: Tic-Tac-Toe Game

on:
  issues:
    types: [opened]

jobs:
  process_move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'move')
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Process move
      run: |
        move=$(echo ${{ github.event.issue.title }} | sed 's/move //')
        python tic_tac_toe.py $move

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update game board"; git push)

    - name: Close issue
      uses: peter-evans/close-issue@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        comment: "Move processed. Check the README for the updated game board."
